baseURL = "https://example.com/"
title = "Hugo Theme Tailwind Example Site"
author = "陳芝瑄"
copyright = "陳芝瑄"
pagination.pagerSize = 10
languageCode = "en-us"
theme = "tailwind"

[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "selfie.jpeg"
    title = ""

  [params.footer]
    since = 2025
    poweredby = false

[social_media]
  [[social_media.items]]
    enabled = false
    title = 'Facebook'
    icon = 'brand-facebook'
    link = 'https://www.facebook.com/'

  [[social_media.items]]
    enabled = false
    title = 'X'
    icon = 'brand-x'
    link = 'https://x.com/'

  [[social_media.items]]
    enabled = false
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://www.instagram.com/'

  [[social_media.items]]
    enabled = false
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/'

  [[social_media.items]]
    enabled = false
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/tomowang'

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"